on: [push, pull_request]
name: CI
jobs:
  build:
    name: "Build on Racket '${{ matrix.racket-version }}' (${{ matrix.racket-variant }})"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        racket-version: ["current"]
        racket-variant: ["CS"]
    steps:
      - uses: actions/checkout@master
      - uses: Bogdanp/setup-racket@v0.10
        with:
          architecture: x64
          distribution: full
          variant: ${{ matrix.racket-variant }}
          version: ${{ matrix.racket-version }}
      - run: |
             sudo raco pkg install --auto -i --no-setup --skip-installed typed-racket-test
      - run: xvfb-run racket -l typed-racket-test -- --just `racket -e '(displayln (collection-file-path "succeed/gui-lang.rkt" "typed-racket-test"))'`
